# Vignette

Now that you have explored this forestry data set it is time to present what you have learned to the broader community. You will create and present suggestions on the management of these forests to community leaders, using the data science tools you have developed throughout the semester. 

*We should flesh this out a little more.*

--------------------------------------------------------------------------------
# WORKSHOP: Learning goals (More for us as a team, rather than for SKC students)

The goal of the first day of the this forestry module is to have the students full explore what creating and presenting recommendations for management based on data science means with a strong emphasis on how to best make and present graphs that are accessible and helpful for the general public. 

--------------------------------------------------------------------------------

# Outlining your presentation

## Determining your audience
  
  The first step to making an effective presentation is having a clear picture of what you are trying to present. This comes from having a clear overview of what the main outcomes of your data analysis are as well as what type of audience you are interested in presenting to and what type of information is most relevant to them.
  
  First up lets work to identify the audience you are presenting to. Who would be involved in the process of deciding where to set up a new forestry area? Are there multiple groups that would be interested involved in this process or just one? Who is included in these decision making groups? If you have identified multiple groups that would be involved in this process, for the sake of this exercise select one group you would like to present to. 
  
  Once you have identified who you will be giving your presentation to lets narrow down what kind of presentation they will be most interested in. What kind of background do they have in forestry? What kind of data do you think they would find most helpful in deciding where to set up this forest plot? 
  
## Determining What Data to Focus on

# Refining your graphs

Different types of grpahs for different data. 

## Adding context

This section should be about adding titles, axis labels, and captions with the goal of giving context to the plot that is most tailored to the audience of interest. 
Should we also add legends in this area? 

## Adding visual elements

This sections is about how graphs are a way to convey information visually and so the visual elements of the graph should fit in this goal. 
Introducing themes as a way of giving more control over the visual elements of your graph. *This seems like a good place to reference some online resources*. 
Mentioning that the visuals can be simple or complicated and that as you give more presentations you will figure out waht works for you and for the audience you are presenting to but here are the tools for when you do. 

* Legends (if not above)
* Basic themes
* Ways to make complicated themes
* Colors (and how to make them accessible)
* Shapes and sizes
* Groups, etc. 

# Reviewing your plots

Go back to the beginning of this document and look back at what you identified as the key takeaways from the data analysis. Take this as a chance to reflect on if your choice of graph is the best for summarizing this information

Review how you identified your audience, do your choices of added graph elements benefit this audience? If you could improve the graph in some way, how would you? (even if you don't know how to code this yet)